import { Exo } from "next/font/google";
import "./globals.css";
import Nav from "./Components/Nav";
import Footer from "./Components/Footer";
import ClientLayout from "./ClientLayout";

const exo = Exo({
   variable: "--font-exo",
   subsets: ["latin", "latin-ext", "vietnamese"], // support full unicode ranges
   weight: ["300", "400", "500", "600", "700", "800"], // all weights you want
   display: "swap",
});

export const metadata = {
   title: "PHISH N MITIGATE ",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${exo.variable} antialiased`}>
            <ClientLayout>{children}</ClientLayout>
         </body>
      </html>
   );
}
